# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rohanblueboybaijal/Computer_Vision

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rohanblueboybaijal/Computer_Vision

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rohanblueboybaijal/Computer_Vision/CMakeFiles /home/rohanblueboybaijal/Computer_Vision/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rohanblueboybaijal/Computer_Vision/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named drawing

# Build rule for target.
drawing: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 drawing
.PHONY : drawing

# fast build rule for target.
drawing/fast:
	$(MAKE) -f CMakeFiles/drawing.dir/build.make CMakeFiles/drawing.dir/build
.PHONY : drawing/fast

#=============================================================================
# Target rules for targets named d32

# Build rule for target.
d32: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 d32
.PHONY : d32

# fast build rule for target.
d32/fast:
	$(MAKE) -f CMakeFiles/d32.dir/build.make CMakeFiles/d32.dir/build
.PHONY : d32/fast

#=============================================================================
# Target rules for targets named petcat_face_rec

# Build rule for target.
petcat_face_rec: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 petcat_face_rec
.PHONY : petcat_face_rec

# fast build rule for target.
petcat_face_rec/fast:
	$(MAKE) -f CMakeFiles/petcat_face_rec.dir/build.make CMakeFiles/petcat_face_rec.dir/build
.PHONY : petcat_face_rec/fast

#=============================================================================
# Target rules for targets named gate_detection

# Build rule for target.
gate_detection: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gate_detection
.PHONY : gate_detection

# fast build rule for target.
gate_detection/fast:
	$(MAKE) -f CMakeFiles/gate_detection.dir/build.make CMakeFiles/gate_detection.dir/build
.PHONY : gate_detection/fast

#=============================================================================
# Target rules for targets named morph

# Build rule for target.
morph: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 morph
.PHONY : morph

# fast build rule for target.
morph/fast:
	$(MAKE) -f CMakeFiles/morph.dir/build.make CMakeFiles/morph.dir/build
.PHONY : morph/fast

#=============================================================================
# Target rules for targets named shape

# Build rule for target.
shape: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 shape
.PHONY : shape

# fast build rule for target.
shape/fast:
	$(MAKE) -f CMakeFiles/shape.dir/build.make CMakeFiles/shape.dir/build
.PHONY : shape/fast

#=============================================================================
# Target rules for targets named file_sys

# Build rule for target.
file_sys: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 file_sys
.PHONY : file_sys

# fast build rule for target.
file_sys/fast:
	$(MAKE) -f CMakeFiles/file_sys.dir/build.make CMakeFiles/file_sys.dir/build
.PHONY : file_sys/fast

d32.o: d32.cpp.o

.PHONY : d32.o

# target to build an object file
d32.cpp.o:
	$(MAKE) -f CMakeFiles/d32.dir/build.make CMakeFiles/d32.dir/d32.cpp.o
.PHONY : d32.cpp.o

d32.i: d32.cpp.i

.PHONY : d32.i

# target to preprocess a source file
d32.cpp.i:
	$(MAKE) -f CMakeFiles/d32.dir/build.make CMakeFiles/d32.dir/d32.cpp.i
.PHONY : d32.cpp.i

d32.s: d32.cpp.s

.PHONY : d32.s

# target to generate assembly for a file
d32.cpp.s:
	$(MAKE) -f CMakeFiles/d32.dir/build.make CMakeFiles/d32.dir/d32.cpp.s
.PHONY : d32.cpp.s

drawing.o: drawing.cpp.o

.PHONY : drawing.o

# target to build an object file
drawing.cpp.o:
	$(MAKE) -f CMakeFiles/drawing.dir/build.make CMakeFiles/drawing.dir/drawing.cpp.o
.PHONY : drawing.cpp.o

drawing.i: drawing.cpp.i

.PHONY : drawing.i

# target to preprocess a source file
drawing.cpp.i:
	$(MAKE) -f CMakeFiles/drawing.dir/build.make CMakeFiles/drawing.dir/drawing.cpp.i
.PHONY : drawing.cpp.i

drawing.s: drawing.cpp.s

.PHONY : drawing.s

# target to generate assembly for a file
drawing.cpp.s:
	$(MAKE) -f CMakeFiles/drawing.dir/build.make CMakeFiles/drawing.dir/drawing.cpp.s
.PHONY : drawing.cpp.s

file_sys.o: file_sys.cpp.o

.PHONY : file_sys.o

# target to build an object file
file_sys.cpp.o:
	$(MAKE) -f CMakeFiles/file_sys.dir/build.make CMakeFiles/file_sys.dir/file_sys.cpp.o
.PHONY : file_sys.cpp.o

file_sys.i: file_sys.cpp.i

.PHONY : file_sys.i

# target to preprocess a source file
file_sys.cpp.i:
	$(MAKE) -f CMakeFiles/file_sys.dir/build.make CMakeFiles/file_sys.dir/file_sys.cpp.i
.PHONY : file_sys.cpp.i

file_sys.s: file_sys.cpp.s

.PHONY : file_sys.s

# target to generate assembly for a file
file_sys.cpp.s:
	$(MAKE) -f CMakeFiles/file_sys.dir/build.make CMakeFiles/file_sys.dir/file_sys.cpp.s
.PHONY : file_sys.cpp.s

gate_detection.o: gate_detection.cpp.o

.PHONY : gate_detection.o

# target to build an object file
gate_detection.cpp.o:
	$(MAKE) -f CMakeFiles/gate_detection.dir/build.make CMakeFiles/gate_detection.dir/gate_detection.cpp.o
.PHONY : gate_detection.cpp.o

gate_detection.i: gate_detection.cpp.i

.PHONY : gate_detection.i

# target to preprocess a source file
gate_detection.cpp.i:
	$(MAKE) -f CMakeFiles/gate_detection.dir/build.make CMakeFiles/gate_detection.dir/gate_detection.cpp.i
.PHONY : gate_detection.cpp.i

gate_detection.s: gate_detection.cpp.s

.PHONY : gate_detection.s

# target to generate assembly for a file
gate_detection.cpp.s:
	$(MAKE) -f CMakeFiles/gate_detection.dir/build.make CMakeFiles/gate_detection.dir/gate_detection.cpp.s
.PHONY : gate_detection.cpp.s

morph.o: morph.cpp.o

.PHONY : morph.o

# target to build an object file
morph.cpp.o:
	$(MAKE) -f CMakeFiles/morph.dir/build.make CMakeFiles/morph.dir/morph.cpp.o
.PHONY : morph.cpp.o

morph.i: morph.cpp.i

.PHONY : morph.i

# target to preprocess a source file
morph.cpp.i:
	$(MAKE) -f CMakeFiles/morph.dir/build.make CMakeFiles/morph.dir/morph.cpp.i
.PHONY : morph.cpp.i

morph.s: morph.cpp.s

.PHONY : morph.s

# target to generate assembly for a file
morph.cpp.s:
	$(MAKE) -f CMakeFiles/morph.dir/build.make CMakeFiles/morph.dir/morph.cpp.s
.PHONY : morph.cpp.s

petcat_face_rec.o: petcat_face_rec.cpp.o

.PHONY : petcat_face_rec.o

# target to build an object file
petcat_face_rec.cpp.o:
	$(MAKE) -f CMakeFiles/petcat_face_rec.dir/build.make CMakeFiles/petcat_face_rec.dir/petcat_face_rec.cpp.o
.PHONY : petcat_face_rec.cpp.o

petcat_face_rec.i: petcat_face_rec.cpp.i

.PHONY : petcat_face_rec.i

# target to preprocess a source file
petcat_face_rec.cpp.i:
	$(MAKE) -f CMakeFiles/petcat_face_rec.dir/build.make CMakeFiles/petcat_face_rec.dir/petcat_face_rec.cpp.i
.PHONY : petcat_face_rec.cpp.i

petcat_face_rec.s: petcat_face_rec.cpp.s

.PHONY : petcat_face_rec.s

# target to generate assembly for a file
petcat_face_rec.cpp.s:
	$(MAKE) -f CMakeFiles/petcat_face_rec.dir/build.make CMakeFiles/petcat_face_rec.dir/petcat_face_rec.cpp.s
.PHONY : petcat_face_rec.cpp.s

shape_detection.o: shape_detection.cpp.o

.PHONY : shape_detection.o

# target to build an object file
shape_detection.cpp.o:
	$(MAKE) -f CMakeFiles/shape.dir/build.make CMakeFiles/shape.dir/shape_detection.cpp.o
.PHONY : shape_detection.cpp.o

shape_detection.i: shape_detection.cpp.i

.PHONY : shape_detection.i

# target to preprocess a source file
shape_detection.cpp.i:
	$(MAKE) -f CMakeFiles/shape.dir/build.make CMakeFiles/shape.dir/shape_detection.cpp.i
.PHONY : shape_detection.cpp.i

shape_detection.s: shape_detection.cpp.s

.PHONY : shape_detection.s

# target to generate assembly for a file
shape_detection.cpp.s:
	$(MAKE) -f CMakeFiles/shape.dir/build.make CMakeFiles/shape.dir/shape_detection.cpp.s
.PHONY : shape_detection.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... drawing"
	@echo "... d32"
	@echo "... petcat_face_rec"
	@echo "... gate_detection"
	@echo "... morph"
	@echo "... shape"
	@echo "... file_sys"
	@echo "... d32.o"
	@echo "... d32.i"
	@echo "... d32.s"
	@echo "... drawing.o"
	@echo "... drawing.i"
	@echo "... drawing.s"
	@echo "... file_sys.o"
	@echo "... file_sys.i"
	@echo "... file_sys.s"
	@echo "... gate_detection.o"
	@echo "... gate_detection.i"
	@echo "... gate_detection.s"
	@echo "... morph.o"
	@echo "... morph.i"
	@echo "... morph.s"
	@echo "... petcat_face_rec.o"
	@echo "... petcat_face_rec.i"
	@echo "... petcat_face_rec.s"
	@echo "... shape_detection.o"
	@echo "... shape_detection.i"
	@echo "... shape_detection.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

